version: "3"

services:
  php:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./html:/var/www/html
      - ./news_data:/var/www/news_data
    ports:
      - 8080:80
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./db/data:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    links:
      - mysql
    ports:
       - 8084:80
    volumes:
       - "./phpmyadmin/sessions:/sessions"
